version: "3.8"
services:
  database:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fresk
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/schema.sql:/docker-entrypoint-initdb.d/schema.sql


  app:
      image: paultisaw/fresk-backend-dev:1.0
      container_name: app_container
      ports:
        - "9090:9090"
      depends_on:
        - database
      environment:
        DB_HOST: database
        DB_PORT: 5432
        DB_USER: dbuser
        DB_PASSWORD: 1234
        DB_NAME: fresk

volumes:
  db_data:
